name: Deploy to Production

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to VM
        run: |
          # Copy build files to VM
          gcloud compute scp -r ./dist/* lyudevig@news-explorer.info:/home/lyudevig/news-explorer-frontend

          # Restart web server
          gcloud compute ssh lyudevig@news-explorer.info --command="pm2 restart app"
